### ISSUE TITLE
Sec-Token-Binding-Context header is not defined in draft-ietf-tokbind-ttrp-01

### ISSUE THREAD

**Issue by kasunbg** [zmartzone/mod_token_binding#1]
@zandbelt First, thanks for your wonderful work. I'm reaching out to you for a clarification over the Sec-Token-Binding-Context header that is sent to the back-end servers by mod_token_binding.

[draft-ietf-tokbind-ttrp-01](https://tools.ietf.org/html/draft-campbell-tokbind-tls-term-00) only describe `Sec-Provided-Token-Binding-ID` and `Sec-Referred-Token-Binding-ID` headers. 

I did come across [draft-campbell-tokbind-tls-term-00](https://tools.ietf.org/html/draft-campbell-tokbind-tls-term-00) that describe about a header named `Token-Binding-Context`. It seemed like this header refers to that one. 

May be you kept this header for backward-compatibility reasons? I do not see any issues keeping it, it just confuses us the first time. :) I'm simply looking for a clarification.

Please find a httpbin output retrieved via the HTTPD server run via your docker image.

```
{
  "headers": {
    "Accept": "text/html", 
    "Connection": "close", 
    "Host": "httpbin.org", 
    "Sec-Provided-Token-Binding-Id": "AgBBQBTIBpQkkzv8aCwcfYNeELX8viGOw0rRlcFqhB_MvI_JP_6JzTdR2fKAb1HfDO3vSpwlMA2rjN8hjhf99IKs0As", 
    "Sec-Token-Binding-Context": "AA0CQlNMtfvYwjx1Qv6Hzssmqo61-b6wcRt3ZzRt0IyKsn0", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Chrome/60.0", 
    "X-Forwarded-Host": "localhost:4433", 
    "X-Forwarded-Server": "www.zmartzone.eu"
  }
}
```

Thanks,
KasunG

**Comment by zandbelt** [comment]
Yes, it is for "backwards compatibility" with a feature that could also be useful in certain environments but has been taken out of the more recent draft.

**Comment by kasunbg** [comment]
That is good to know. I see that it has been added to README few days ago. I missed that. 

Btw, would it be better to provide a configuration option to decide which headers we need to send to the backend server? I'm asking because Token-Binding-Context is apparently only need to be added to the requests if it was explicitly configured to do so -- as per draft-campbell-tokbind-tls-term-00#section-2. 

```
   Reverse proxies MUST only add the "Token-Binding-Context" header when
   explicitly configured to do so and MUST only dispatch requests
   containing it to trusted backend servers.  ...
```

Thanks.

**Comment by zandbelt** [comment]
Fair point, though that draft is obsolete now and installing/configuring this module could be seen as the "explicit configuration" that is referred to. But it does make sense to send only what is explicitly required on a per-header basis. FWIW: I'll take a PR any time ;-)

**Comment by kasunbg** [comment]
Cool. I was reading a bit on whether there is a rule for Sec-Provided-Token-Binding-Id header as well. [draft-ietf-tokbind-ttrp-01 section-3](https://tools.ietf.org/html/draft-ietf-tokbind-ttrp-01#section-3) says that producing these headers SHOULD be an configuration option. Default should be to not use the headers.

I'm interested in providing a PR. But, I need your input on how the configuration in httpd.conf should look like. Do you have any suggestions?

I fiddled with nginx token binding module a bit. This is their way of configuring it which uses [custom variables](https://github.com/google/ngx_token_binding#variables).

```
upstream example.com {
   ip_hash;
   server localhost:9443;
   server localhost:9444;
}

server {
   listen 443;
   server_name example;
   token_binding on;


   location / {
      proxy_pass https://example.com;
      proxy_http_version 1.1;

      proxy_set_header Sec-Provided-Token-Binding-Id $provided_token_binding_id;
      proxy_set_header Sec-Referred-Token-Binding-Id $referred_token_binding_id;
   }

   ssl on;
   ssl_certificate /usr/local/nginx/ssl/nginx.crt;
   ssl_certificate_key /usr/local/nginx/ssl/nginx.key;
   
   access_log /var/log/nginx/access.log;
}

```

Thanks.

**Comment by zandbelt** [comment]
I'd suggest:
`TokenBindingPassVariable [provided|referred|context|all]+`

**Comment by zandbelt** [comment]
It turned out as:
```
TokenBindingPassVar [provided|referred|context]+
```
with the default being all of them.
